# Generated by Django 6.0.4 on 2026-04-27 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('admin', 'Админ'), ('manager', 'Менеджер'), ('senior_manager', 'Старший менеджер'), ('reader', 'Читатель')], default='reader', max_length=20, verbose_name='Роль'),
        ),
    ]
