# Generated by Django 6.0.4 on 2026-05-01 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_customuser_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='timezone',
            field=models.CharField(default='Asia/Baku', max_length=50, verbose_name='Часовой пояс'),
        ),
    ]
