# Generated by Django 6.0.4 on 2026-06-05 08:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_customuser_timezone'),
        ('warehouses', '0005_warehousetransfer'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='warehouses.warehouse', verbose_name='Привязанный склад'),
        ),
    ]
