# Generated by Django 6.0.4 on 2026-04-20 09:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0001_initial'),
        ('warehouses', '0004_rename_name_warehouse_city'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trading',
            options={'ordering': ['-created_at'], 'verbose_name': 'История склада', 'verbose_name_plural': 'История склада'},
        ),
        migrations.AddField(
            model_name='trading',
            name='quantity_after',
            field=models.IntegerField(default=0, verbose_name='Количество после'),
        ),
        migrations.AddField(
            model_name='trading',
            name='quantity_before',
            field=models.IntegerField(default=0, verbose_name='Количество до'),
        ),
        migrations.AddField(
            model_name='trading',
            name='warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trades', to='warehouses.warehouse', verbose_name='Склад'),
        ),
        migrations.AlterField(
            model_name='trading',
            name='quantity',
            field=models.PositiveIntegerField(verbose_name='Количество'),
        ),
        migrations.AlterField(
            model_name='trading',
            name='trade_type',
            field=models.CharField(choices=[('sell', 'Продажа'), ('purchase', 'Покупка')], max_length=20, verbose_name='Тип операции'),
        ),
    ]
