# Generated by Django 6.0.4 on 2026-04-21 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0002_alter_trading_options_trading_quantity_after_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trading',
            name='comment',
            field=models.TextField(blank=True, null=True, verbose_name='Комментарий'),
        ),
        migrations.AddField(
            model_name='trading',
            name='name',
            field=models.CharField(default='Без названия', max_length=255, verbose_name='Название сделки'),
            preserve_default=False,
        ),
    ]
