# Generated by Django 6.0.4 on 2026-04-22 09:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_initial'),
        ('trading', '0003_trading_comment_trading_name'),
        ('warehouses', '0004_rename_name_warehouse_city'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trading',
            options={'ordering': ['-created_at'], 'verbose_name': 'Сделка', 'verbose_name_plural': 'Сделки'},
        ),
        migrations.CreateModel(
            name='TradingItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(verbose_name='Количество')),
                ('quantity_before', models.IntegerField(default=0, verbose_name='Количество до')),
                ('quantity_after', models.IntegerField(default=0, verbose_name='Количество после')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trading_items', to='products.product', verbose_name='Товар')),
                ('trading', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='trading.trading', verbose_name='Сделка')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trading_items', to='warehouses.warehouse', verbose_name='Склад')),
            ],
            options={
                'verbose_name': 'Позиция сделки',
                'verbose_name_plural': 'Позиции сделки',
            },
        ),
    ]
