# Generated by Django 6.0.4 on 2026-04-23 08:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0004_alter_trading_options_tradingitem'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trading',
            options={'ordering': ['-created_at'], 'verbose_name': 'История склада', 'verbose_name_plural': 'История склада'},
        ),
        migrations.CreateModel(
            name='TradingAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='trades/attachments/%Y/%m/%d/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('trade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='trading.trading')),
            ],
        ),
    ]
