# Generated by Django 6.0.4 on 2026-04-24 06:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_initial'),
        ('trading', '0005_alter_trading_options_tradingattachment'),
        ('warehouses', '0004_rename_name_warehouse_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trading',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trades', to='products.product', verbose_name='Товар'),
        ),
        migrations.AlterField(
            model_name='trading',
            name='quantity',
            field=models.PositiveIntegerField(default=0, verbose_name='Количество'),
        ),
        migrations.AlterField(
            model_name='trading',
            name='warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trades', to='warehouses.warehouse', verbose_name='Склад'),
        ),
    ]
