# Generated by Django 6.0.4 on 2026-04-24 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0006_alter_trading_product_alter_trading_quantity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradingitem',
            name='fulfilled_quantity',
            field=models.PositiveIntegerField(default=0, verbose_name='Отдали'),
        ),
        migrations.AddField(
            model_name='tradingitem',
            name='requested_quantity',
            field=models.PositiveIntegerField(default=0, verbose_name='Нужно'),
        ),
    ]
