# Generated by Django 6.0.4 on 2026-04-27 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0007_tradingitem_fulfilled_quantity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trading',
            name='status',
            field=models.CharField(choices=[('pending', 'В процессе'), ('completed', 'Завершена')], default='pending', max_length=20, verbose_name='Статус'),
        ),
    ]
