# Generated by Django 6.0.4 on 2026-04-28 06:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0008_trading_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TradingAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trading_id_snapshot', models.PositiveIntegerField(blank=True, null=True, verbose_name='ID сделки')),
                ('action', models.CharField(choices=[('created', 'Создание'), ('updated', 'Редактирование'), ('fulfilled', 'Дополнение'), ('deleted', 'Удаление'), ('rollback', 'Откат склада')], max_length=20, verbose_name='Действие')),
                ('description', models.TextField(verbose_name='Описание')),
                ('before_data', models.JSONField(blank=True, default=dict, verbose_name='Было')),
                ('after_data', models.JSONField(blank=True, default=dict, verbose_name='Стало')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата')),
                ('trading', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='trading.trading', verbose_name='Сделка')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trading_audit_logs', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Аудит сделки',
                'verbose_name_plural': 'Аудит сделок',
                'ordering': ['-created_at'],
            },
        ),
    ]
