# Generated by Django 6.0.4 on 2026-04-29 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0009_tradingauditlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trading',
            name='quantity',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Количество'),
        ),
        migrations.AlterField(
            model_name='trading',
            name='quantity_after',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Количество после'),
        ),
        migrations.AlterField(
            model_name='trading',
            name='quantity_before',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Количество до'),
        ),
        migrations.AlterField(
            model_name='tradingauditlog',
            name='trading_id_snapshot',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='ID сделки'),
        ),
        migrations.AlterField(
            model_name='tradingitem',
            name='fulfilled_quantity',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Отдали'),
        ),
        migrations.AlterField(
            model_name='tradingitem',
            name='quantity',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Количество'),
        ),
        migrations.AlterField(
            model_name='tradingitem',
            name='quantity_after',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Количество после'),
        ),
        migrations.AlterField(
            model_name='tradingitem',
            name='quantity_before',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Количество до'),
        ),
        migrations.AlterField(
            model_name='tradingitem',
            name='requested_quantity',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Нужно'),
        ),
    ]
