# Generated by Django 6.0.4 on 2026-04-29 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0010_alter_trading_quantity_alter_trading_quantity_after_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tradingauditlog',
            name='trading_id_snapshot',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='ID сделки'),
        ),
    ]
