# Generated by Django 6.0.4 on 2026-04-29 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0011_alter_tradingauditlog_trading_id_snapshot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trading',
            name='quantity',
            field=models.PositiveIntegerField(default=0, verbose_name='Количество'),
        ),
        migrations.AlterField(
            model_name='trading',
            name='quantity_after',
            field=models.IntegerField(default=0, verbose_name='Количество после'),
        ),
        migrations.AlterField(
            model_name='trading',
            name='quantity_before',
            field=models.IntegerField(default=0, verbose_name='Количество до'),
        ),
        migrations.AlterField(
            model_name='tradingitem',
            name='fulfilled_quantity',
            field=models.PositiveIntegerField(default=0, verbose_name='Отдали'),
        ),
        migrations.AlterField(
            model_name='tradingitem',
            name='quantity',
            field=models.PositiveIntegerField(default=0, verbose_name='Количество'),
        ),
        migrations.AlterField(
            model_name='tradingitem',
            name='quantity_after',
            field=models.IntegerField(default=0, verbose_name='Количество после'),
        ),
        migrations.AlterField(
            model_name='tradingitem',
            name='quantity_before',
            field=models.IntegerField(default=0, verbose_name='Количество до'),
        ),
        migrations.AlterField(
            model_name='tradingitem',
            name='requested_quantity',
            field=models.PositiveIntegerField(default=0, verbose_name='Нужно'),
        ),
    ]
