# Generated by Django 6.0.4 on 2026-05-01 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0013_tradingcomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradingcomment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Обновлено'),
        ),
    ]
