# Generated by Django 6.0.4 on 2026-06-19 07:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0009_remove_product_price_delete_productpricehistory'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ShipmentTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient_name', models.CharField(max_length=255, verbose_name='Получатель / компания')),
                ('destination', models.CharField(max_length=255, verbose_name='Куда отправить')),
                ('recipient_contact', models.CharField(blank=True, max_length=255, verbose_name='Контакт получателя')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('status', models.CharField(choices=[('new', 'Новое'), ('seen', 'Увидел'), ('shipped', 'Отправлено'), ('problem', 'Проблема')], default='new', max_length=20, verbose_name='Статус')),
                ('seen_at', models.DateTimeField(blank=True, null=True, verbose_name='Когда увидел')),
                ('shipped_at', models.DateTimeField(blank=True, null=True, verbose_name='Когда отправлено')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('assigned_to', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assigned_shipment_tasks', to=settings.AUTH_USER_MODEL, verbose_name='Кому поручено')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_shipment_tasks', to=settings.AUTH_USER_MODEL, verbose_name='Кто создал')),
            ],
            options={
                'verbose_name': 'Задание на отправку',
                'verbose_name_plural': 'Задания на отправку',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ShipmentTaskItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(verbose_name='Количество')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shipment_task_items', to='products.product', verbose_name='Товар')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='shipments.shipmenttask', verbose_name='Задание')),
            ],
            options={
                'verbose_name': 'Товар в задании на отправку',
                'verbose_name_plural': 'Товары в задании на отправку',
            },
        ),
    ]
