# Generated by Django 6.0.4 on 2026-06-19 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shipmenttask',
            name='destination',
        ),
        migrations.RemoveField(
            model_name='shipmenttask',
            name='recipient_contact',
        ),
        migrations.AlterField(
            model_name='shipmenttask',
            name='recipient_name',
            field=models.CharField(max_length=255, verbose_name='Кому отправить'),
        ),
    ]
