# Generated by Django 6.0.4 on 2026-04-16 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_remove_inventory_unique_product_warehouse_and_more'),
        ('warehouses', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Warehouse',
        ),
    ]
