# Generated by Django 6.0.4 on 2026-04-17 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warehouses', '0003_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='warehouse',
            old_name='name',
            new_name='city',
        ),
    ]
