name: Trigger auto deployment for warehouse

on:
  push:
    branches:
      - master
    paths:
      - '**'
      - '.github/workflows/warehouse-AutoDeployTrigger-*.yml'

  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write  # Нужно для авторизации через OIDC
      contents: read   # Нужно для чтения кода из репозитория

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.WAREHOUSE_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.WAREHOUSE_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.WAREHOUSE_AZURE_SUBSCRIPTION_ID }}

      - name: Build and deploy to Container App
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          containerAppName: warehouse
          resourceGroup: Warehouse
          dockerfilePath: Dockerfile  # Убедись, что файл называется именно Dockerfile и лежит в корне проекта
