# Generated by Django 6.0.4 on 2026-04-16 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='inventory',
            name='unique_product_warehouse',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='product',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='warehouse',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.DeleteModel(
            name='Inventory',
        ),
    ]
