# Generated by Django 6.0.4 on 2026-04-29 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='unit',
            field=models.CharField(choices=[('pcs', 'шт'), ('kg', 'кг')], default='pcs', max_length=10, verbose_name='Единица измерения'),
        ),
    ]
