# Generated by Django 6.0.4 on 2026-04-29 13:29

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_productpricehistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='productpricehistory',
            name='change_type',
            field=models.CharField(choices=[('initial', 'Цена при создании'), ('update', 'Обновление цены')], default='update', max_length=20, verbose_name='Тип изменения'),
        ),
        migrations.AlterField(
            model_name='productpricehistory',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
