# Generated by Django 6.0.4 on 2026-05-05 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_productpricehistory_change_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
        migrations.DeleteModel(
            name='ProductPriceHistory',
        ),
    ]
