# Generated by Django 6.0.4 on 2026-06-29 07:02

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_remove_product_price_delete_productpricehistory'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='normalized_code',
            field=models.CharField(blank=True, db_index=True, max_length=255, verbose_name='Нормализованный код'),
        ),
        migrations.CreateModel(
            name='ProductImportBatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(default='Импорт товаров', max_length=255, verbose_name='Название импорта')),
                ('file', models.FileField(upload_to='product_imports/', verbose_name='Excel файл')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('checked', 'Проверен'), ('imported', 'Импортирован'), ('cancelled', 'Отменён')], default='draft', max_length=20, verbose_name='Статус')),
                ('total_rows', models.PositiveIntegerField(default=0)),
                ('existing_count', models.PositiveIntegerField(default=0)),
                ('similar_code_count', models.PositiveIntegerField(default=0)),
                ('similar_name_count', models.PositiveIntegerField(default=0)),
                ('new_count', models.PositiveIntegerField(default=0)),
                ('error_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_import_batches', to=settings.AUTH_USER_MODEL, verbose_name='Кто загрузил')),
            ],
            options={
                'verbose_name': 'Импорт товаров',
                'verbose_name_plural': 'Импорты товаров',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductImportRow',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('row_number', models.PositiveIntegerField(verbose_name='Строка Excel')),
                ('raw_code', models.CharField(blank=True, max_length=255, verbose_name='Код из Excel')),
                ('normalized_code', models.CharField(blank=True, db_index=True, max_length=255, verbose_name='Очищенный код')),
                ('raw_name', models.TextField(blank=True, verbose_name='Название из Excel')),
                ('raw_unit', models.CharField(blank=True, max_length=50, verbose_name='Единица из Excel')),
                ('detected_status', models.CharField(choices=[('existing', 'Уже есть в базе'), ('similar_code', 'Похожий код'), ('similar_name', 'Похожее название'), ('duplicate_in_file', 'Дубль внутри Excel'), ('new', 'Новый товар'), ('error', 'Ошибка')], default='new', max_length=30, verbose_name='Что нашёл сайт')),
                ('action', models.CharField(choices=[('skip', 'Пропустить'), ('create', 'Создать новый товар'), ('link', 'Привязать к существующему')], default='skip', max_length=20, verbose_name='Решение админа')),
                ('note', models.TextField(blank=True, verbose_name='Комментарий проверки')),
                ('is_processed', models.BooleanField(default=False, verbose_name='Обработано')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rows', to='products.productimportbatch', verbose_name='Импорт')),
                ('created_product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_from_import_rows', to='products.product', verbose_name='Созданный товар')),
                ('selected_product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='selected_import_rows', to='products.product', verbose_name='Выбранный товар')),
                ('suggested_product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='suggested_import_rows', to='products.product', verbose_name='Похожий товар в базе')),
            ],
            options={
                'verbose_name': 'Строка импорта товаров',
                'verbose_name_plural': 'Строки импорта товаров',
                'ordering': ['batch', 'row_number'],
                'constraints': [models.UniqueConstraint(fields=('batch', 'row_number'), name='unique_product_import_batch_row')],
            },
        ),
    ]
