# Generated by Django 6.0.4 on 2026-06-29 07:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_product_normalized_code_productimportbatch_and_more'),
        ('warehouses', '0005_warehousetransfer'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimportbatch',
            name='created_products_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='productimportbatch',
            name='duplicate_in_file_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='productimportbatch',
            name='import_type',
            field=models.CharField(choices=[('products_only', 'Только товары'), ('products_with_stock', 'Товары + остатки на склад')], default='products_only', max_length=30, verbose_name='Тип импорта'),
        ),
        migrations.AddField(
            model_name='productimportbatch',
            name='linked_rows_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='productimportbatch',
            name='quantity_error_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='productimportbatch',
            name='quantity_mode',
            field=models.CharField(choices=[('replace', 'Заменить остатки на складе'), ('add', 'Прибавить к текущим остаткам')], default='replace', max_length=20, verbose_name='Как обновлять количество'),
        ),
        migrations.AddField(
            model_name='productimportbatch',
            name='skipped_rows_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='productimportbatch',
            name='target_warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_import_batches', to='warehouses.warehouse', verbose_name='Склад для остатков'),
        ),
        migrations.AddField(
            model_name='productimportbatch',
            name='updated_inventory_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='productimportrow',
            name='inventory_after',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Остаток стал'),
        ),
        migrations.AddField(
            model_name='productimportrow',
            name='inventory_before',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Остаток был'),
        ),
        migrations.AddField(
            model_name='productimportrow',
            name='inventory_updated',
            field=models.BooleanField(default=False, verbose_name='Остаток обновлён'),
        ),
        migrations.AddField(
            model_name='productimportrow',
            name='quantity',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Количество'),
        ),
        migrations.AddField(
            model_name='productimportrow',
            name='raw_quantity',
            field=models.CharField(blank=True, max_length=100, verbose_name='Количество из Excel'),
        ),
        migrations.AlterField(
            model_name='productimportrow',
            name='detected_status',
            field=models.CharField(choices=[('existing', 'Уже есть в базе'), ('similar_code', 'Похожий код'), ('similar_name', 'Похожее название'), ('duplicate_in_file', 'Дубль внутри Excel'), ('new', 'Новый товар'), ('error', 'Ошибка'), ('quantity_error', 'Ошибка количества')], default='new', max_length=30, verbose_name='Что нашёл сайт'),
        ),
    ]
