# Generated by Django 6.0.4 on 2026-07-01 10:59

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_productimportbatch_created_products_count_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimportbatch',
            name='quantity_mode',
            field=models.CharField(choices=[('replace', 'Заменить остатки на складе'), ('add', 'Прибавить к текущим остаткам')], default='add', max_length=20, verbose_name='Как обновлять количество'),
        ),
        migrations.CreateModel(
            name='ProductCodeAlias',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('alias_code', models.CharField(db_index=True, max_length=255, verbose_name='Вариант кода')),
                ('normalized_alias_code', models.CharField(blank=True, db_index=True, max_length=255, verbose_name='Нормализованный вариант кода')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed_product_code_aliases', to=settings.AUTH_USER_MODEL, verbose_name='Кто подтвердил')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='code_aliases', to='products.product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Вариант кода товара',
                'verbose_name_plural': 'Варианты кодов товаров',
                'ordering': ['product__name', 'alias_code'],
                'constraints': [models.UniqueConstraint(fields=('alias_code',), name='unique_product_code_alias')],
            },
        ),
    ]
